apiVersion: core.choreo.dev/v1alpha1
kind: Component
metadata:
  name: fastapi-app
spec:
  type: Service
  build:
    env: python
    version: "3.10"
    command: ["pip", "install", "-r", "requirements.txt"]
    run: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
  inbound:
    - name: http
      type: REST
      port: 8080
      context: /
      expose: true
  scaling:
    minReplicas: 1
    maxReplicas: 2
